### imports

In [2]:
import csv
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling
from sklearn.compose import ColumnTransformer

### import dataset

In [36]:
dataset = pd.read_csv('Data.csv')
# Splitting the attributes into independent and dependent attributes
X = dataset.iloc[:, :-1].values # attributes to determine dependent variable / Class
Y = dataset.iloc[:, -1].values # dependent variable / Class
print(dataset)
print(X)
print(Y)


   Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes
[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 nan]
 ['India' 40.0 69600.0]
 ['Brazil' nan 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Handle missing data

In [38]:
# handling the missing data and replace missing values with nan from numpy and replace with mean of all the other values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])
print(X)

[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 76533.33333333333]
 ['India' 40.0 69600.0]
 ['Brazil' 43.77777777777778 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]


### encode categorical data

In [48]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X = columnTransformer.fit_transform(X)
print('X=', X)
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print('Y=', Y)

X= [[0.0 1.0 0.0 1.0 0.0 49.0 86400.0]
 [1.0 0.0 1.0 0.0 0.0 32.0 57600.0]
 [0.0 1.0 0.0 0.0 1.0 35.0 64800.0]
 [1.0 0.0 1.0 0.0 0.0 43.0 73200.0]
 [0.0 1.0 0.0 0.0 1.0 45.0 76533.33333333333]
 [0.0 1.0 0.0 1.0 0.0 40.0 69600.0]
 [1.0 0.0 1.0 0.0 0.0 43.77777777777778 62400.0]
 [0.0 1.0 0.0 1.0 0.0 53.0 94800.0]
 [0.0 1.0 0.0 0.0 1.0 55.0 99600.0]
 [0.0 1.0 0.0 1.0 0.0 42.0 80400.0]]
Y= [0 1 0 0 1 1 0 1 0 1]


### training and testing dataset

In [58]:
# splitting the dataset into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_test)
print(Y_test)
test = pd.DataFrame(X_test)
test

[[0.0 1.0 0.0 0.0 1.0 35.0 64800.0]
 [0.0 1.0 0.0 0.0 1.0 55.0 99600.0]]
[0 0]


0    1    2    3    4     5        6
0  0.0  1.0  0.0  0.0  1.0  35.0  64800.0
1  0.0  1.0  0.0  0.0  1.0  55.0  99600.0

### feature scaling

In [3]:
# feature scaling

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
x_df_train = pd.DataFrame(X_train)
x_df_train
x_df_test = pd.DataFrame(X_test)
x_df_test

NameError: name 'X_train' is not defined